# frontend/app.yaml
# This is the secure version of the frontend service configuration.

runtime: custom
env: flex

# --- Environment Variables ---
# These are variables that App Engine will provide to our running service.
env_variables:
  GCP_PROJECT: ${GAE_PROJECT}
  GCP_REGION: 'us-central1'
  TASK_QUEUE: 'mastering-queue'
  # --- THIS IS THE FIX ---
  # We are now passing the Firebase config via a SECURE build-time variable.
  # This keeps the secret API key out of our source code.
  FIREBASE_CONFIG_JSON: ${FIREBASE_CONFIG_JSON}

service: default
instance_class: F1
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2





