# This is the final, correct configuration for a long-running background task worker.
# It uses a Backend instance type (B-class) and manual scaling to eliminate timeouts.

runtime: python311
service: staging
entrypoint: gunicorn -b :$PORT main:app

# Use a Backend instance class, which is designed for long-running processes
# and does not have the 60-second request timeout. A B4 instance provides
# ample memory (1024MB) and CPU for audio processing.
instance_class: B4

# Use manual scaling to ensure an instance is always ready to process tasks.
# This also bypasses the short timeouts associated with automatic scaling.
# 'instances: 1' is perfect for a staging/development queue.
manual_scaling:
  instances: 1

