service: staging
runtime: custom
env: flex

# Resource allocation for the flexible environment instances.
# UPGRADED: Doubled the CPU and Memory to handle large audio files.
resources:
  cpu: 2
  memory_gb: 4
  disk_size_gb: 10
  
automatic_scaling:
  # The syntax is max_num_instances for Flex
  min_num_instances: 1
  max_num_instances: 2
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.7

