# This configuration is for the 'staging' service.
# It uses a MEMORY-OPTIMIZED instance class for large file processing.
service: staging
runtime: custom
env: flex

# Upgraded to a memory-optimized instance (M1)
# This provides more RAM to handle the final file concatenation.
instance_class: M1

# The M1 class requires manual scaling settings.
manual_scaling:
  instances: 1

