# This file configures your Google App Engine service.
# It uses 'basic_scaling' which is the correct way to handle
# long-running background tasks in modern App Engine environments.

runtime: python311
instance_class: F2
service: staging
entrypoint: gunicorn -b :$PORT main:app

# --- THIS IS THE FIX ---
# Switch from 'automatic_scaling' to 'basic_scaling'.
# This allows for longer-running instances that are ideal for
# background processing jobs like audio mastering.
basic_scaling:
  # Sets the instance to shut down after 15 minutes of inactivity.
  idle_timeout: 15m
  # Specifies the maximum number of instances to create.
  max_instances: 2

