# This configuration is for the 'staging' service.
# It uses a heavy-duty B8 backend instance with manual scaling to
# definitively solve any and all memory issues for large file processing.
service: staging
runtime: custom
env: flex

# Specifies the powerful, memory-heavy backend instance class
instance_class: B8

# Manual scaling is REQUIRED for larger instance classes like B8.
# This keeps one powerful instance running for our worker tasks.
manual_scaling:
  instances: 1


