# This configuration is for the 'staging' service.
# It uses a heavy-duty B8 backend instance with manual scaling.
service: staging
runtime: custom
env: flex

instance_class: B8

manual_scaling:
  instances: 1

# This value has been slightly changed to force a full service update.
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1
  cool_down_period_sec: 181
  cpu_utilization:
    target_utilization: 0.7