# This is the final, correct configuration for a long-running background task worker.
# It uses a Backend instance class (B8) and manual scaling to eliminate infrastructure timeouts.
# The entrypoint now includes the --timeout 600 flag to prevent the Gunicorn
# master process from killing long-running worker tasks.

runtime: python311
service: staging

# Add the --timeout 600 flag to the gunicorn command.
# This gives each worker up to 10 minutes to complete a task,
# solving the internal Gunicorn timeout issue.
entrypoint: gunicorn --timeout 600 -b :$PORT main:app

# A B8 instance provides enough RAM (2048MB) for audio processing.
instance_class: B8

# Manual scaling ensures an instance is always ready for tasks.
manual_scaling:
  instances: 1

