# This file configures your Google App Engine service.
# It includes the F2 instance class to prevent memory errors and the
# entrypoint to correctly start the production server.

runtime: python311
instance_class: F2
service: staging

# --- THIS IS THE FIX ---
# The 'entrypoint' tells App Engine how to start your Flask app
# using the Gunicorn production web server. 'main:app' means:
# "In the file named 'main.py', find the Flask app object named 'app'".
# The '-b :$PORT' part tells Gunicorn to bind to the port provided
# by the App Engine environment.
entrypoint: gunicorn -b :$PORT main:app

automatic_scaling:
  min_instances: 0
  max_instances: 2

