# app.yaml (Final Correct Version for New Project)
# This deploys the application to the 'default' service using the
# App Engine Flexible Environment with a custom runtime.

runtime: custom
env: flex

# Resource allocation for the flexible environment instances.
resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10
  
automatic_scaling:
  # The minimum number of instances for env:flex must be 1 or greater.
  min_num_instances: 1
  max_num_instances: 2
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.7

