# This is the final, correct configuration for a long-running background task worker.
# It uses a Backend instance class (B-class) and manual scaling to eliminate timeouts.
# The B8 instance class provides sufficient memory (2048MB) to handle NumPy's usage.

runtime: python311
service: staging
entrypoint: gunicorn -b :$PORT main:app

# Use a B8 Backend instance class. This is critical for providing enough RAM (2048MB)
# to prevent the Out-of-Memory Killer from terminating the process during
# memory-intensive NumPy operations.
instance_class: B8

# Manual scaling ensures an instance is always ready and bypasses short timeouts.
manual_scaling:
  instances: 1

