# This configuration is for the 'staging' service.
# It uses a heavy-duty B8 backend instance with the correct manual_scaling.
service: staging
runtime: custom
env: flex

instance_class: B8

# Manual scaling is REQUIRED for larger instance classes like B8.
# This keeps one powerful instance running for our worker tasks.
manual_scaling:
  instances: 1

    
    


