# This is the master blueprint for our Google App Engine application.
# This version uses the modern, explicit entrypoint syntax required
# by the Python 3.11 runtime.

runtime: python311

# This is the corrected, modern syntax for the startup command.
entrypoint: gunicorn --bind : --workers 1 --threads 8 --timeout 0 main:app

instance_class: F2

automatic_scaling:
  min_instances: 0
  max_instances: 1
