# This file configures your Google App Engine service.
# It includes the F2 instance class, the Gunicorn entrypoint,
# and the crucial timeout setting to allow for long-running tasks.

runtime: python311
instance_class: F2
service: staging
entrypoint: gunicorn -b :$PORT main:app

automatic_scaling:
  min_instances: 0
  max_instances: 2
  
  # --- THIS IS THE FIX ---
  # By default, App Engine stops any request that takes longer
  # than 60 seconds. This setting increases that deadline to the
  # maximum of 10 minutes (600 seconds), giving your audio
  # processing enough time to complete.
  request_timeout: 600s

