# This tells App Engine to use the flexible environment with a custom runtime.
# It requires a Dockerfile to be present.
runtime: custom
env: flex

# Explicitly define the service as "default". This is crucial.
service: default

# App Engine Flexible needs at least one scaling setting.
automatic_scaling:
  min_num_instances: 1

